// node scripts/embed-fonts.mjs
import { writeFileSync, mkdirSync } from "fs";

const BASE = "https://raw.githubusercontent.com/googlefonts/roboto/main/src/hinted";
const FONTS = [
  { name: "ROBOTO_REGULAR", url: `${BASE}/Roboto-Regular.ttf` },
  { name: "ROBOTO_BOLD",    url: `${BASE}/Roboto-Bold.ttf` },
  { name: "ROBOTO_ITALIC",  url: `${BASE}/Roboto-Italic.ttf` },
];

console.log("Pobieranie fontów z CDN...");

const results = await Promise.all(
  FONTS.map(async ({ name, url }) => {
    console.log(`  Fetching ${name}...`);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
    const buf = await res.arrayBuffer();
    const b64 = Buffer.from(buf).toString("base64");
    console.log(`  ${name}: ${buf.byteLength} bytes → ${b64.length} chars base64`);
    return `export const ${name} = "data:font/truetype;base64,${b64}";`;
  })
);

const output = "// Auto-generated by scripts/embed-fonts.mjs — do not edit manually\n" + results.join("\n") + "\n";

mkdirSync("lib/export", { recursive: true });
writeFileSync("lib/export/fonts-b64.ts", output, "utf8");
console.log("\nGotowe: lib/export/fonts-b64.ts");
